* JIM Core
jim-core provides the core functionality of a Java identifier name miner, a tool to extract identifier names from Java source code files for later analysis. jim-core currently processes Java code that conforms to Java 8. Java 9/10/11 processing is not yet implemented

** Alpha
jim-core is  currently being developed and is very much alpha software. It is error-prone and the API is subject to change, especially as functionality is added and refined.

** Usage
Binaries are released to Maven central, so Gradle users should add the following line to their build file:

#+begin_src
  compile 'uk.org.facetus:jim-core:0.0.12'
#+end_src

The API is currently minimalist and easy to use. For example:

#+begin_src java  
    Jim library = new Jim();
    NameExtractor n = library.create();
    try {
        FileData d = n.process( "FileName.java" );
		...
    }
    catch (FileNotFoundException e) { ... }
    catch (IOException e) { ... }
    catch (JimParserException e) { ... }
#+end_src

The ~FileData~ class provides methods to recover the names and tokens found in the processed file as well as tokenised names. Names retain the capitalisation used by the software developers and the tokens are normalised to lower case. Tokens may also be tagged with a list of the word lists in which they were found.



** Requirements and Dependencies

The jim-core library requires Java 8 to run. It has not been fully tested with Java 9/10/11 (yet). 

jim-core uses ANTLR4 to parse Java and the Apache Commons Collections v4. Identifier name processing relies on intt and idtk-j. JUnit 4 and Hamcrest 1.3 are used for unit testing. The following illustrates the dependencies for Gradle.

#+begin_src 
    compile 'org.antlr:antlr4-runtime:4.8'
    compile 'uk.org.facetus:idtk-j:0.5.5'
    compile 'uk.org.facetus:intt:0.8.10'
    compile 'org.apache.commons:commons-collections4:4.1'
    
    testImplementation 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
#+end_src

** Build
A pom.xml is provided. For other build systems see the list of dependencies above. 


