/*
 * Copyright (C) 2019 Simon Butler
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.facetus.jim.core;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 * A set of utilities.
 * 
 */
public class Utils {
    
    public Utils() { throw new UnsupportedOperationException(); }
    
    /**
     * Indicates if a Java source code file might have been generated by 
     * software. The risk with this method is that the caller opens a file
     * once to test it and then again to process it. However, the caller 
     * gains by not needing to process the generated file. In other words, 
     * there is a penalty for many files and a saving for generated files. 
     * @param sourceFile
     * @return a boolean indicating whether the inspected file may have been 
     * generated by software
     * @throws FileNotFoundException
     * @throws IOException 
     */
    public static boolean isGenerated( File sourceFile ) throws FileNotFoundException, IOException {
        boolean isGenerated = false;
        try (BufferedReader in = new BufferedReader( new java.io.FileReader( sourceFile ) )) {
            int lineCount = 0;
            final int linesToRead = 100; // should be in the first few lines, but be safe, just in case of licence statements.
            String line;
            while ( (line = in.readLine()) != null && lineCount < linesToRead ) {
                if ( line.matches( "\\/\\/ \\$ANTLR.*" )
                        || line.matches( "\\/\\* Generated.*(JavaCC|JJTree).*" )
                        || line.matches( "^.*\\* Generated by the IDL-to-Java compiler.*$" )
                        || line.matches( "^.*\\* This file was auto-generated.*$" )// apache axis, which has changed statements. The version used is a compromise to catch different versions
                        || line.matches( "^.*Generated by the protocol buffer compiler.*$" ) // google web toolkit
                        || line.matches( "^.*generated by make_pydocs\\.py.*$" ) // jython
                        || line.matches( "^.*Generated file, do not modify.*$" ) // jython
                        ) {
                    isGenerated = true;
                    break;
                }
                lineCount++;
            }
        }

        return isGenerated;
    }
}
